remote_theme: pixeldroid/programming-pages
layout: page
title: User Guide
plugins:
- jemoji
#title: User Guide
#remote_theme: pmarsceill/just-the-docs
#color_scheme: "light"
#search_enabled: false
#heading_anchors: true
#back_to_top: true
#back_to_top_text: "Back to top"
#gh_edit_link: false
#kramdown:
#  syntax_highlighter_opts:
#    block:
#      line_numbers: false
